// GENERATED by scripts/build.mjs from config/links.json + src/core.js — do not edit by hand.
export const CONFIG = {
  "timezone": "America/Chicago",
  "fallback": "https://mybadalibi.com/",
  "links": {
    "babyshower": {
      "url": "https://www.amazon.com/dp/B0CQXVFBM6"
    },
    "birthday": {
      "url": "https://www.amazon.com/dp/B0CPWHC9X6"
    },
    "halloween": {
      "url": "https://www.amazon.com/dp/B0FJG4WTVV"
    },
    "benny": {
      "url": "https://www.amazon.com/dp/B0DFR22QZL"
    },
    "nighty": {
      "url": "https://www.amazon.com/dp/B0FKTPV2JV"
    },
    "food": {
      "url": "https://www.amazon.com/dp/B0FKRB76LB"
    },
    "baking": {
      "url": "https://www.amazon.com/dp/B0D1R18W74"
    },
    "wordsearch": {
      "url": "https://play.google.com/store/apps/details?id=com.badalibi.wordsearch"
    },
    "countmoney": {
      "url": "https://play.google.com/store/apps/details?id=com.badalibi.countmoney"
    },
    "codebrown": {
      "url": "https://play.google.com/store/apps/details?id=com.badalibi.codebrown"
    },
    "shop": {
      "url": "https://mybadalibi.com/books"
    },
    "halloween-color": {
      "url": "https://www.amazon.com/dp/B0CLH4Z7D6"
    },
    "mars": {
      "url": "https://www.amazon.com/s?k=9798289087218"
    }
  }
};

// Bad Alibi /go/<slug> redirect + privacy-friendly click counter.
// Runs on Cloudflare Workers / Pages Functions (also importable from Node for tests).
//
// Privacy: stores ONLY aggregate counters keyed by
//   (day, slug, referrer-domain, src-tag, kind)  ->  count
// No IP addresses, cookies, user agents, full referrer URLs, or any per-visitor identifier
// are ever stored. The User-Agent is inspected in memory only to separate link-preview bots
// from human clicks, then discarded.

export const RESERVED_STATS = '_stats';
const SLUG_RE = /^[a-z0-9][a-z0-9-]{0,63}$/;
const SRC_RE = /^[a-z0-9_-]{1,32}$/;
const HOST_RE = /^[a-z0-9.-]{1,253}$/;
const BOT_RE = /bot|crawl|spider|slurp|facebookexternalhit|facebookcatalog|meta-externalagent|embedly|preview|whatsapp|telegram|discord|slack|skype|vkshare|pinterest|linkedin|bitly|curl|wget|python-requests|httpclient|okhttp|go-http-client|headless|lighthouse|monitor|uptime/i;

export const SCHEMA_SQL = `CREATE TABLE IF NOT EXISTS clicks (
  day   TEXT NOT NULL,
  slug  TEXT NOT NULL,
  ref   TEXT NOT NULL DEFAULT '',
  src   TEXT NOT NULL DEFAULT '',
  kind  TEXT NOT NULL DEFAULT 'click',
  count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (day, slug, ref, src, kind)
) WITHOUT ROWID`;

const UPSERT_SQL = `INSERT INTO clicks (day, slug, ref, src, kind, count) VALUES (?1, ?2, ?3, ?4, ?5, 1)
  ON CONFLICT (day, slug, ref, src, kind) DO UPDATE SET count = count + 1`;

// ---------- validation ----------
export function validateConfig(config) {
  const errors = [];
  if (!config || typeof config !== 'object') return ['config must be an object'];
  if (!config.links || typeof config.links !== 'object') errors.push('config.links missing');
  try { new URL(config.fallback); } catch { errors.push('config.fallback must be an absolute URL'); }
  if (config.timezone) {
    try { new Intl.DateTimeFormat('en-CA', { timeZone: config.timezone }); } catch { errors.push(`bad timezone ${config.timezone}`); }
  }
  for (const [slug, entry] of Object.entries(config.links || {})) {
    if (!SLUG_RE.test(slug)) errors.push(`bad slug "${slug}"`);
    let u;
    try { u = new URL(entry && entry.url); } catch { errors.push(`slug "${slug}": url is not absolute`); continue; }
    if (u.protocol !== 'https:') errors.push(`slug "${slug}": url must be https`);
  }
  return errors;
}

// ---------- helpers ----------
export function dayString(date, timeZone) {
  // en-CA formats as YYYY-MM-DD
  return new Intl.DateTimeFormat('en-CA', {
    timeZone: timeZone || 'UTC', year: 'numeric', month: '2-digit', day: '2-digit'
  }).format(date);
}

export function referrerDomain(refHeader) {
  if (!refHeader) return '';
  try {
    const u = new URL(refHeader);
    if (u.protocol !== 'http:' && u.protocol !== 'https:') return '';
    let h = u.hostname.toLowerCase().replace(/^www\./, '').replace(/^m\./, '').replace(/^l\./, '').replace(/^lm\./, '');
    if (!HOST_RE.test(h)) return '';
    return h.slice(0, 100);
  } catch {
    return '';
  }
}

export function srcTag(value) {
  if (!value) return '';
  const v = String(value).toLowerCase();
  return SRC_RE.test(v) ? v : '';
}

export function isBot(ua) {
  if (!ua) return true; // real browsers always send a UA
  return BOT_RE.test(ua);
}

function parseSlug(pathname, prefix) {
  // pathname like /go/benny or /go/benny/ ; prefix like /go
  if (pathname === prefix || pathname === prefix + '/') return { kind: 'index' };
  if (!pathname.startsWith(prefix + '/')) return { kind: 'none' };
  let rest = pathname.slice(prefix.length + 1);
  if (rest.endsWith('/')) rest = rest.slice(0, -1);
  try { rest = decodeURIComponent(rest); } catch { return { kind: 'unknown' }; }
  rest = rest.toLowerCase();
  if (rest === RESERVED_STATS) return { kind: 'stats' };
  if (!SLUG_RE.test(rest)) return { kind: 'unknown' };
  return { kind: 'slug', slug: rest };
}

function timingSafeEqual(a, b) {
  if (typeof a !== 'string' || typeof b !== 'string') return false;
  const len = Math.max(a.length, b.length);
  let diff = a.length ^ b.length;
  for (let i = 0; i < len; i++) diff |= (a.charCodeAt(i) || 0) ^ (b.charCodeAt(i) || 0);
  return diff === 0;
}

// ---------- stores ----------
export class D1Store {
  constructor(db) { this.db = db; this.initialized = false; }
  async init() {
    if (this.initialized) return;
    await this.db.prepare(SCHEMA_SQL).run();
    this.initialized = true;
  }
  async increment({ day, slug, ref, src, kind }) {
    const stmt = () => this.db.prepare(UPSERT_SQL).bind(day, slug, ref, src, kind);
    try {
      await stmt().run();
    } catch (err) {
      if (/no such table/i.test(String(err && err.message))) { await this.init(); await stmt().run(); }
      else throw err;
    }
  }
  async rows({ from, to }) {
    try {
      const res = await this.db
        .prepare('SELECT day, slug, ref, src, kind, count FROM clicks WHERE day >= ?1 AND day <= ?2 ORDER BY day, slug, kind, ref, src')
        .bind(from, to).all();
      return res.results || [];
    } catch (err) {
      if (/no such table/i.test(String(err && err.message))) return [];
      throw err;
    }
  }
}

export class MemoryStore {
  constructor() { this.map = new Map(); }
  async increment({ day, slug, ref, src, kind }) {
    const k = JSON.stringify([day, slug, ref, src, kind]);
    this.map.set(k, (this.map.get(k) || 0) + 1);
  }
  async rows({ from, to }) {
    const out = [];
    for (const [k, count] of this.map) {
      const [day, slug, ref, src, kind] = JSON.parse(k);
      if (day >= from && day <= to) out.push({ day, slug, ref, src, kind, count });
    }
    return out.sort((a, b) => (a.day + a.slug + a.kind + a.ref + a.src).localeCompare(b.day + b.slug + b.kind + b.ref + b.src));
  }
}

export function storeFromEnv(env) {
  if (env && env.GOLINKS_DB) return new D1Store(env.GOLINKS_DB);
  if (env && env.__memoryStore) return env.__memoryStore; // tests
  return null; // redirects still work; counting disabled
}

// ---------- stats ----------
export function aggregate(rows, group) {
  if (group === 'detail') return rows.map(r => ({ day: r.day, slug: r.slug, kind: r.kind, ref: r.ref, src: r.src, count: Number(r.count) }));
  const acc = new Map();
  for (const r of rows) {
    const key = group === 'total' ? r.slug : r.day + '|' + r.slug;
    let o = acc.get(key);
    if (!o) { o = group === 'total' ? { slug: r.slug, clicks: 0, bot_hits: 0 } : { day: r.day, slug: r.slug, clicks: 0, bot_hits: 0 }; acc.set(key, o); }
    if (r.kind === 'bot') o.bot_hits += Number(r.count); else o.clicks += Number(r.count);
  }
  return [...acc.values()];
}

export function toCSV(objs) {
  if (!objs.length) return '';
  const cols = Object.keys(objs[0]);
  const esc = v => { const s = String(v ?? ''); return /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s; };
  return [cols.join(','), ...objs.map(o => cols.map(c => esc(o[c])).join(','))].join('\n') + '\n';
}

async function handleStats(request, env, config, store, url) {
  const token = env && env.STATS_TOKEN;
  if (!token) return new Response('Not found', { status: 404, headers: { 'cache-control': 'no-store' } });
  const auth = request.headers.get('authorization') || '';
  const given = auth.startsWith('Bearer ') ? auth.slice(7) : (url.searchParams.get('token') || '');
  if (!timingSafeEqual(given, token)) return new Response('Unauthorized', { status: 401, headers: { 'cache-control': 'no-store', 'www-authenticate': 'Bearer' } });
  if (!store) return new Response('Counting storage not configured (bind a D1 database as GOLINKS_DB)', { status: 503 });

  const tz = config.timezone || 'UTC';
  const today = dayString(new Date(), tz);
  const dateRe = /^\d{4}-\d{2}-\d{2}$/;
  const from = dateRe.test(url.searchParams.get('from') || '') ? url.searchParams.get('from') : '0000-01-01';
  const to = dateRe.test(url.searchParams.get('to') || '') ? url.searchParams.get('to') : today;
  const groupParam = url.searchParams.get('group');
  const group = ['daily', 'total', 'detail'].includes(groupParam) ? groupParam : 'daily';
  const format = url.searchParams.get('format') === 'csv' ? 'csv' : 'json';
  const data = aggregate(await store.rows({ from, to }), group);
  const headers = { 'cache-control': 'no-store', 'x-robots-tag': 'noindex' };
  if (format === 'csv') {
    return new Response(toCSV(data), { headers: { ...headers, 'content-type': 'text/csv; charset=utf-8', 'content-disposition': `attachment; filename="golinks-${group}-${from}-to-${to}.csv"` } });
  }
  return new Response(JSON.stringify({ timezone: tz, from, to, group, rows: data }, null, 2), { headers: { ...headers, 'content-type': 'application/json; charset=utf-8' } });
}

// ---------- main entry ----------
// handleGo(request, env, ctx, config) -> Response | null (null = path not under prefix)
export async function handleGo(request, env, ctx, config, options = {}) {
  const prefix = options.prefix || '/go';
  const url = new URL(request.url);
  const parsed = parseSlug(url.pathname, prefix);
  if (parsed.kind === 'none') return null;

  const store = options.store || storeFromEnv(env);
  if (parsed.kind === 'stats') {
    if (request.method !== 'GET') return new Response('Method not allowed', { status: 405, headers: { allow: 'GET' } });
    return handleStats(request, env, config, store, url);
  }
  if (request.method !== 'GET' && request.method !== 'HEAD') {
    return new Response('Method not allowed', { status: 405, headers: { allow: 'GET, HEAD' } });
  }

  let slugKey, destination;
  if (parsed.kind === 'slug' && Object.prototype.hasOwnProperty.call(config.links, parsed.slug)) {
    slugKey = parsed.slug;
    destination = config.links[parsed.slug].url;
  } else {
    // Never echo arbitrary user input into storage: unknown slugs share one bucket.
    slugKey = parsed.kind === 'index' ? '_index' : '_unknown';
    destination = config.fallback;
  }

  const response = new Response(null, {
    status: 302,
    headers: {
      location: destination,
      'cache-control': 'private, no-store, max-age=0',
      'referrer-policy': 'no-referrer',
      'x-robots-tag': 'noindex, nofollow'
    }
  });

  if (request.method === 'GET' && store) {
    const record = {
      day: dayString(options.now ? options.now() : new Date(), config.timezone),
      slug: slugKey,
      ref: referrerDomain(request.headers.get('referer')),
      src: srcTag(url.searchParams.get('src')),
      kind: isBot(request.headers.get('user-agent')) ? 'bot' : 'click'
    };
    const p = store.increment(record).catch(err => console.error('golinks: count failed', err && err.message));
    if (ctx && typeof ctx.waitUntil === 'function') ctx.waitUntil(p); else await p;
  }
  return response;
}
